console.log("goodevening did you eat dinner? 입니다.")
console.log("goodevening did you eat dinner? 입니다.")
console.log("goodevening did you eat dinner? 입니다.")
console.log("goodevening did you eat dinner? 입니다.")
console.log("test2 pull main하기 위해 commit 메시지 한 줄 추가")
console.log("한줄만 더 추가하자.")
console.log("이번에는 test2에서 2-issue로 수정해보자.")
console.log("코드 수정하기 전에 우선 나좀 작업하고 있을게~~")
